---
- name  :  Install apache  
  hosts :  air
  become:  yes


  tasks:
 
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  - name: Install Apache web server
    apt:  name=apache2  state=latest

  - name: Start Apache and enable it
    service: name=apache2 state=started enabled=yes     

  - name: Create index.html
    raw: "echo Welcome to my RaspBerryPi/Air Apache2 | sudo tee /var/www/html/index.html"   