---
- name  :  Install apache  
  hosts :  air
  become:  yes


  tasks:
 
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  - name: Un-Install Apache web server
    apt:  name=apache2  state=absent
  - debug: 
      msg:  "apache2 web server uninstalled" 

  - name: Un-Install NGINX web server
    apt:  name=nginx  state=absent
  - debug: 
     msg:  "nginx web server uninstalled"
