---
- name  :  Variables
  hosts :  wpvisit
  #hosts :  jenk
  become:  yes

  vars:
    message1: TEST message 1
    message2: TEST message 2
    secret:  1234567890
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'

  tasks:

  - name: Print "secret" variable
    debug:
      var: secret

  - debug:
      msg: "Secter password: {{ secret }}"
  
  - debug: 
      msg: "Server owner: {{ ansible_user }}"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ ansible_user }}"
      
  - debug:
      var: full_message   

  - debug:
      var: ansible_distribution

  - shell: |
      whoami
      uptime
    register: result1
  
  - shell:  cat /etc/shadow
    register: result3

  - debug:
      var: result1.stdout 
  
  - debug:
      var: result3.stdout_lines 
