---
- name: My Super Playbook
  hosts: all
  become: yes

  vars:
    mytext: "Hello from IT"

  tasks:
  - name: Ping test
    ping:

   
  - include: create_folders.yml
  - include: create_files.yml
