---
- name: Install default Apache Web Server
  hosts: all 
  become: yes

  tasks:
  - name: Install Apache WebServer
    apt: name=apache2 state=latest

  
  - name: Start Apache and Enable it on thr every boot
    service: name=apache2 state=started enabled=yes
