---
# handlers file for deploy_apache_web
- name: RestartApacheDebian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
 

- name: RestartApacheRedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"
