---
# tasks file for deploy_apache_web
- block:    # ==== Block for DEBIAN LINUX ====
    - name: Update apt-get repo and cache
      apt: 
         update_cache: yes 
         force_apt_get: yes 
         cache_valid_time: 3600
    - name: Install Apache web server
      apt:  
         name: apache2  
         state: latest
    - name: Start Apache and enable it
      service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"

- block:    # ==== Block for RedHat LINUX ====
    - name: Yum Update 
      yum: 
         update_cache: yes 
    - name: Install Apache web server
      yum:  
         name: httpd  
         state: latest
    - name: Start Apache and enable it
      service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"

- name:  Generate Index.html for MyWebsite
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
  notify: 
    - RestartApacheRedHat
    - RestartApacheDebian
 
- name: Copy files to Web Server
  copy: src={{ item }} dest={{ destin_folder }} mode=0555
  loop:
    - "Glacier.jpg"
    - "Sunrise.jpg"
    - "crazy.jpg"
    - "lake.jpg"
  notify: 
    - RestartApacheRedHat
    - RestartApacheDebian
