---
# tasks file for deploy_apache_web
- name: CHECK and Print LINUX Version
  debug: 
    var: ansible_os_family 

- block:  # DEBIAN #

    - name: Install Apache Web Server for Debian
      apt: name=apache2 state=latest

    - name: Start WebServer and make it enable on boot for Debian 
      service: name=apache2 state=started enabled=yes

  when: ansible_os_family == "Debian"

- block:  # REDHAT #

    - name: Install Apache Web Server for RedHat
      yum: name=httpd state=latest

    - name: Start WebServer and make it enable on boot
      service: name=httpd state=started enabled=yes

  when: ansible_os_family == "RedHat"

- name: Generate INDEX.HTML file
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
  notify: 
    - Restart Apache Debian
    - Restart Apache RedHat 

- name: Copy MyHomePage to Servers
  copy: src={{ item }} dest={{ destin_folder }} mode=0555
  loop:
    - "crazy.jpg"
    - "Sunrise.jpg"
    - "Glacier.jpg"
    - "lake.jpg"
  notify: 
    - Restart Apache Debian
    - Restart Apache RedHat 
